# Generated by Django 4.0.4 on 2022-05-29 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.CharField(default=uuid.UUID('d16f63fa-abf6-4e43-bea7-56baec540048'), max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fechaDeNacimiento', models.DateField()),
                ('profesion', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
